---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: {{ .Release.Name }}-canary
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector: *labels
