---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: {{ .Release.Name }}
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ .Release.Name }}
  progressDeadlineSeconds: 600
  service:
    port: 8080
    targetPort: 8080
    portDiscovery: true
  skipAnalysis: {{ .Values.canary.skipAnalysis }}
  analysis:
    interval: 10s
    threshold: 20
    maxWeight: 80
    stepWeight: 10
    metrics:
      - name: {{ .Release.Name }}
        templateRef:
          name: {{ .Release.Name }}
          namespace: {{ .Release.Namespace }}
        thresholdRange:
          min: 0.99
        interval: 1m
    webhooks:
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger
        timeout: 10s
        metadata:
          type: bash
          cmd: 'curl http://sample-app-canary.sample-app.svc.cluster.local:8080/success -H "Host: sample.app" -v'
      - name: k6-load-test
        timeout: 5m
        type: rollout
        url: http://k6-loadtester.flagger:8000/launch-test
        metadata:
          script: |
            import http from 'k6/http';
            import {check} from 'k6';

            export const options = {
              scenarios: {
                load: {
                  executor: 'constant-arrival-rate',
                  duration: '30s',
                  rate: 20,
                  timeUnit: '1s',
                  preAllocatedVUs: 20,
                },
              },
              thresholds: {
                'checks': ['rate>0.9'],
                'http_req_duration': ['p(95)<1000'],
              },
            };

            export default function () {
              const params = {
                headers: {
                'Host': 'sample.app',
                'Content-Type': 'application/json',
                },
              };

              const res = http.get(`http://sample-app-canary.sample-app.svc.cluster.local:8080/success`, params);
              check(res, {
                'status code is 200': (r) => r.status === 200,
                'node is kind-control-plane': (r) => r.json().node === 'kind-control-plane',
                'namespace is sample-app': (r) => r.json().namespace === 'sample-app',
                'pod is sample-app-*': (r) => r.json().pod.includes('sample-app-'),
                'deployment is canary': (r) => r.json().deployment === 'sample-app',
              });
            }
