apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  provider:
    type: prometheus
    address: http://prometheus-operated.prometheus.svc.cluster.local:9090
  query: |
    sum(rate(
      sample_app_requests_count{service="{{ "{{ service }}" }}-canary", success="true"}[{{ "{{ interval }}" }}])
    ) by (service)
    /
    sum(rate(
      sample_app_requests_count{service="{{ "{{ service }}" }}-canary"}[{{ "{{ interval }}" }}])
    ) by (service)
    unless sum(rate(
      sample_app_requests_count{service="{{ "{{ service }}" }}-canary"}[{{ "{{ interval }}" }}])
    ) by (service) == 0
